Repository inventree/inventree-website, pull requests merged in 2022-11, with the labels that each got.

#52 Add webrick to make running in dev mode on *nix simpler
  Gemfile
  Gemfile.lock
Labels: dependencies

#68 fix rss link rendering
  _layouts/collection/collection_index.html
Labels: bug

#78 [Blog] Translation
  _posts/2021-11-22-translation.md
  assets/blog/2022-11-22-translation.png
Labels: blog
